config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :index, :show] do
    resources :goals, only: [:new, :edit, :update, :show]
    resources :comments, only: [:create]
  end
  
  resources :goals, only: [:create, :destroy] do
    resources :comments, only: [:create]
  end
  
  resource :session, only: [:new, :create, :destroy]
  
  root to: "users#home"
end

app/models/comment.rb
class Comment < ActiveRecord::Base  
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :goal, presence: true
  validates :top_secret, inclusion: { in: [false, true] }
  
  belongs_to(
    :achiever,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  
  has_many :comments, as: :commentable
  
  after_initialize :ensure_top_secret
  
  private
  
  def ensure_top_secret
    self.top_secret ||= false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}
  
  after_initialize :ensure_session_token
  
  has_many :goals
  has_many :comments, as: :commentable
  has_many(
    :authored_comments,
    class_name: "Comment",
    foreign_key: :user_id,
    primary_key: :id
  )
   
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def password
    @password
  end
  
  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end
  
  def generate_token
    SecureRandom.base64(16)
  end
  
  def reset_session_token!
    self.session_token = generate_token
    self.save
    self.session_token
  end
  
  def public_goals
    goals.where(top_secret: false)
  end
  
  private
  
  def ensure_session_token
    self.session_token ||= generate_token
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def signin!(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def signout!(user)
    session[:session_token] = nil
    user.reset_session_token!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @comment = @user.comments.new(comments_params)
    @comment.user_id = current_user.id
    
    @comment.save
    flash[:errors] = @comment.errors.full_messages
    redirect_to user_url(@user)
  end
  
  private
  
  def comments_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_logged_in, only: [:new, :create]
  
  def new
    render :new
  end
  
  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to user_url(@goal.achiever)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end
  
  def edit
    @goal = Goal.find(params[:id])
    @user = User.find(params[:user_id])
    render :edit
  end
  
  def update
    @user = User.find(params[:user_id])
    @goal = Goal.find(params[:id])
    @goal.top_secret = false unless params[:goal][:top_secret]
    if @goal.update(goal_params)
      redirect_to user_url(@goal.achiever)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end  
  end
  
  def destroy
    @goal = Goal.find(params[:id])
    under_achiever = @goal.achiever
    @goal.destroy
    redirect_to user_url(under_achiever)
  end
  
  private
  
  def goal_params
    params.require(:goal).permit(:goal, :top_secret)
  end
  
  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def destroy
    signout!(current_user)
    redirect_to root_url
  end
  
  def create
    @user = User.find_by_credentials(
       params[:user][:username],
       params[:user][:password]
    )
    if @user
      signin!(@user)
      redirect_to root_url
    else
      flash[:errors] = 'Username or password is invalid'
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end
  
  def home
    render :home
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      signin!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @goals = current_user == @user ? @user.goals : @user.public_goals
    @comments = @user.comments
    render :show
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def auth_input
    "<input type='hidden'
            name='authenticity_token'
            value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit goal</h1>

<form action="<%= user_goal_url(@user, @goal) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH" >
  <%= auth_input %>
  
  <label>
    Goal
    <input type="text" 
      name="goal[goal]" 
      value="<%= @goal.goal %>">
      
  </label>
  
  <label>
    Top Secret
  <input type="checkbox" 
    name="goal[top_secret]" 
    value="true"
    id="goal_top_secret"
    <%= "checked" if @goal.top_secret %> > 
  </label>
  
  <input type="submit" value="Update goal">
</form>

app/views/goals/new.html.erb
<h1>Create new goal</h1>

<form action="<%= goals_url %>" method="POST">
  <%= render 'layouts/auth_input' %>
  
  <label>
    Goal
    <input type="text" name="goal[goal]">
  </label>
  
  <label>
    Top Secret
  <input type="checkbox" 
    name="goal[top_secret]" 
    value="true">
  </label>
  
  <input type="submit" value="Create goal">
</form>

app/views/layouts/_auth_input.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <%= "Hi #{ current_user.username }"%>
  <%= button_to "Sign out", session_url, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AchievementsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/errors' %>
<%= yield %>

</body>
</html>

app/views/users/home.html.erb
<% if logged_in? %>
  <h1>Welcome <%= current_user.username %></h1>
<% else %>
    <%= link_to "Sign in", new_session_url %>
    <%= link_to "Sign up", new_user_url %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
  <%= link_to user.username, user_url(user)%>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<form action="<%= users_url %>" method="post">
  <%= render 'layouts/auth_input' %>
  
  <label>
    Username
    <input type="text" name="user[username]">
  </label>
  
  <label>
    Password
    <input type="password" name="user[password]">
  </label>
  
  <input type="submit" value="Sign up">
</form>

app/views/users/show.html.erb
<h1>Welcome</h1>

<h3>My Goals</h3>
<ul>
<% @goals.each do |goal|%>
<li>  <%= goal.goal %>
  <% if current_user == @user %>
    <%= link_to "Edit goal", edit_user_goal_url(@user, goal) %>
    <%= button_to "Delete goal", goal_url(goal), method: :delete %> 
  <% end %>
</li>
<% end %>

</ul>

<h4>Comments</h4>
<ul>
<% @comments.each do |comment| %>
  <li><%= comment.body %></li>
<% end %>  
</ul>

<h4>Say Hi</h4>

<form action="<%= user_comments_url(@user)%>" method="POST">
  <%= auth_input %>
  
  <label>Comment
    <textarea name="comment[body]"></textarea>
  </label>
  
  <input type="submit" value="Add Comment">
</form>